# Generated by Django 4.0.3 on 2022-04-07 22:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_locations_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('north_loc', models.SmallIntegerField()),
                ('east_loc', models.SmallIntegerField()),
                ('district', models.PositiveSmallIntegerField(choices=[(1, 'North'), (2, 'Center'), (3, 'Jerusalem'), (4, 'South')], default=3)),
                ('min_till_doctor', models.SmallIntegerField()),
                ('is_private', models.BooleanField()),
                ('er_type', models.PositiveSmallIntegerField(choices=[(1, 'Hospital'), (2, 'Bikur_Rofe'), (3, 'Terem')], default=1)),
                ('care_fields', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'All'), (1, 'Gastroenterology'), (2, 'Gynaecology'), (3, 'Cardiology'), (4, 'Dendistry'), (5, 'Psychiatry'), (6, 'Orthopedic'), (7, 'Surgery')], default=0, max_length=15)),
            ],
        ),
    ]
